### ISSUE TITLE
issue in compiling with slum-21.08, plz help

### ISSUE THREAD

**Issue by pankajd-57** [mercanca/spart#16]
gcc -lslurm  spart.c -o spart -I/opt/slurm-21.08/include -L/opt/slurm-21.08/lib 
.
.
/usr/bin/ld: spart.c:(.text+0x7b16): undefined reference to `slurm_free_partition_info_msg'
/usr/bin/ld: spart.c:(.text+0x7b25): undefined reference to `slurm_free_ctl_conf'
collect2: error: ld returned 1 exit status

or

gcc -lslurm -lslurmdb spart.c -o spart -I/opt/slurm-21.08/include -L/opt/slurm-21.08/lib
.
.
.

      |                                                          ^
spart.c:752:9: note: ‘snprintf’ output between 4 and 8194 bytes into a destination of size 4096
  752 |         snprintf(mem_result, SPART_INFO_STRING_SIZE, ",%s(%s)",
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  753 |                  spfeatures[j].gres_name, strtmp);
      |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/bin/ld: cannot find -lslurmdb
collect2: error: ld returned 1 exit status

**Comment by mercanca** [comment]
Please check /opt/slurm-21.08/lib directory:
ls -alh /opt/slurm-21.08/lib
If it is true try to change order of the -lslurm parameter: 
gcc  spart.c -o spart -I/opt/slurm-21.08/include -L/opt/slurm-21.08/lib -lslurm
