### ISSUE TITLE
libslurmdb was rolled into libslurm in SLURM 19.05

### ISSUE THREAD

**Issue by alanorth** [mercanca/spart#5]
As of [SLURM 19.05 `libslurmdb` has been rolled into libslurm](https://github.com/SchedMD/slurm/blob/master/RELEASE_NOTES). You now need to compile with the following:

```
$ gcc -lslurm spart.c -o spart
```

**Comment by mercanca** [comment]
Thank you for your warning. I 'll modify compiling text.
